openapi: 3.0.0
info:
  title: Mi API
  description: Descripción de mi API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /github/data:
    get:
      summary: Obtener datos de GitHub
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor
  /module1/data:
    get:
      summary: Obtener datos del módulo 1
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor
  /module2/data:
    get:
      summary: Obtener datos del módulo 2
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor
  /user:
    post:
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Usuario creado exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
