openapi: 3.0.0
info:
  title: Mi API
  description: Descripción de mi API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /user:
    post:
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Usuario creado exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
  /user/followers/following:
    post:
      summary: Crear repositorios del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Repositorios creados exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
  /repositories:
    post:
      summary: Crear repositorios del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Repositorios creados exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
  /repositories/collaborators:
    post:
      summary: Crear repositorios del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Repositorios creados exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
  /repositories/issues/assignees:
    post:
      summary: Crear repositorios del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Repositorios creados exitosamente
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
